micronaut:
  application:
    name: statswhiz
  server:
    port: 8081
---
datasources:
  default:
    url: jdbc:postgresql://localhost:5431/statswhiz2
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
    schema-generate: CREATE_DROP
    dialect: POSTGRES
---
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
